# Generated by Django 3.1.3 on 2021-01-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_image_carousel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image_carousel',
            new_name='ImageCarousel',
        ),
        migrations.RenameModel(
            old_name='Imagen_producto',
            new_name='ImagenProducto',
        ),
        migrations.AlterModelOptions(
            name='imagecarousel',
            options={'verbose_name': 'Imagenes del carrusel', 'verbose_name_plural': 'Imagen del carrusel'},
        ),
        migrations.AlterField(
            model_name='producto',
            name='caracteristica',
            field=models.ManyToManyField(to='tienda.Caracteristica'),
        ),
    ]
