# Generated by Django 3.1.3 on 2021-01-28 23:44

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_auto_20210124_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecarousel',
            name='imagen',
            field=stdimage.models.StdImageField(blank=True, help_text='Tamaño recomendado 1600 X 600', null=True, upload_to='productos/carousel'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=stdimage.models.StdImageField(blank=True, help_text='Tamaño recomendado 350 X 350', null=True, upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='caracteristica',
            field=models.ManyToManyField(to='tienda.Caracteristica'),
        ),
    ]
