# Generated by Django 3.1.3 on 2021-02-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_auto_20210202_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='caracteristica',
            field=models.ManyToManyField(to='tienda.Caracteristica'),
        ),
    ]
