# Generated by Django 3.1.3 on 2021-02-02 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Descripcion')),
                ('Followers', models.IntegerField(default=0, verbose_name='Seguidores')),
                ('Following', models.IntegerField(default=0, verbose_name='Seguidos')),
                ('Friends', models.IntegerField(default=0, verbose_name='Amigos')),
                ('image_profile', stdimage.models.StdImageField(blank=True, help_text='Tamaño recomendado 350 X 350', null=True, upload_to='profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImagesBio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bio', stdimage.models.StdImageField(blank=True, help_text='Tamaño recomendado 350 X 350', null=True, upload_to='profile')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestorUsuarios.profile')),
            ],
            options={
                'verbose_name': 'Imagenes',
                'verbose_name_plural': 'Imagen',
            },
        ),
    ]
