# Generated by Django 3.1.3 on 2021-02-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorUsuarios', '0002_auto_20210202_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Followers',
            new_name='followers',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Following',
            new_name='following',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Friends',
            new_name='friends',
        ),
        migrations.AddField(
            model_name='profile',
            name='busines',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='example', max_length=100, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
