# Generated by Django 3.1.3 on 2021-01-25 00:10

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20210124_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=stdimage.models.StdImageField(upload_to='servicios'),
        ),
    ]
