# Generated by Django 3.1.3 on 2021-01-28 23:44

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_auto_20210124_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=stdimage.models.StdImageField(help_text='Tamaño recomendado 640 X 260', upload_to='servicios'),
        ),
    ]
