# Generated by Django 3.1.3 on 2021-01-29 20:42

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210128_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categorias',
            field=models.ManyToManyField(to='blog.Categoria'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=stdimage.models.StdImageField(blank=True, help_text='Tamaño recomendado 350 X 350', null=True, upload_to='post'),
        ),
    ]
